Repository MissouriMRDT/RoveComm_CPP, pull requests merged in 2024-10, with the labels that each got.

#44 CMake Cleanup and Change C++ Version to C++20
  .github/workflows/tests.yml
  CMakeLists.txt
Labels: enhancement

#43 Add Automation to RoveComm Manifest Updates
  .github/workflows/sync-rovecomm.yml
Labels: enhancement, actions

#46 Make Native Windows Builds Possible
  src/RoveComm/RoveCommGlobals.h
  src/RoveComm/RoveCommPacket.h
  src/RoveComm/RoveCommTCP.cpp
  src/RoveComm/RoveCommTCP.h
  src/RoveComm/RoveCommUDP.cpp
  src/RoveComm/RoveCommUDP.h
Labels: bug, enhancement

#47 Fix Typedef Conflict
  src/RoveComm/RoveCommPacket.h
Labels: bug
