Repository MissouriMRDT/RoveComm_CPP, pull requests merged in 2024-03, with the labels that each got.

#14 Implement an Easier Way to Get Board IPs
  src/RoveComm/RoveCommManifest.h
  tools/RoveComm/parser.py
Labels: enhancement

#17 Non-blocking Sockets and Resource Management
  .clang-format
  .devcontainer/devcontainer.json
  src/RoveComm/RoveCommConsts.h
  src/RoveComm/RoveCommTCP.cpp
  src/RoveComm/RoveCommTCP.h
  src/RoveComm/RoveCommUDP.cpp
  src/RoveComm/RoveCommUDP.h
  src/main.cpp
Labels: bug, enhancement

#19 Fix Release Action and Add AMD64 Library Package
  .github/workflows/deploy_rovecomm.yml
  CMakeLists.txt
  tools/valgrind/run_valgrind.sh
Labels: bug, enhancement

#20 Fix parser so that it doesn't miss boards without any commands.
  src/RoveComm/RoveCommManifest.h
  tools/RoveComm/parser.py
Labels: bug

#21 Add Method for Getting Threadpool Queue Length
  src/interfaces/AutonomyThread.hpp
Labels: enhancement

#24 Fixed Float and Double Data Corruption. Use Proper Network Bit Formats
  src/RoveComm/RoveCommPacket.cpp
  src/RoveComm/RoveCommPacket.h
  src/RoveComm/RoveCommTCP.cpp
  src/RoveComm/RoveCommUDP.cpp
Labels: bug, enhancement

#26 Upgrade BS::thread_pool to 4.0.1
  external/threadpool/BSThreadPool.hpp
  external/threadpool/README.md
  src/interfaces/AutonomyThread.hpp
Labels: enhancement

#28 Fix Failing Deploy Action
  .github/workflows/deploy_rovecomm.yml
Labels: bug

#29 Update Enums, Docker, Valgrind, and Macros
  .devcontainer/Dockerfile_Jammy
  .devcontainer/Dockerfile_JetPack
  .github/workflows/codeql.yml
  .github/workflows/doxygen_generate.yml
  .github/workflows/tests.yml
  .github/workflows/valgrind.yml
  CMakeLists.txt
  src/RoveComm/RoveCommManifest.h
  src/RoveCommLoggers.cpp
  src/RoveCommLoggers.h
  src/interfaces/AutonomyThread.hpp
  src/main.cpp
  src/util/IPS.hpp
  tools/RoveComm/parser.py
  tools/valgrind/run_valgrind.sh
Labels: bug, enhancement

#30 Fix Quill Errors
  src/RoveCommLoggers.cpp
Labels: bug

#31 Fix Installer Builder
  CMakeLists.txt
Labels: bug, enhancement, actions
